tools/vunit: add constr_list parameter to write_makefile
The write_makefile method signature in ToolVunitSim was missing the
constr_list parameter that is passed by commands.py:makefile().

This feature was introduced with commit 94b09e30 ("feature: split
design files and constraints with back compatibility") from #57

This fixes the following:
CRITICAL        main.py:116: hdlmake()  ToolMakefile.makefile_setup() missing 1 required positional argument: 'constr_list'